import { useState } from "react";
import "../public/App.css";

function App() {
  const [allStudents, setAllStudents] = useState([
    {
      roll_no: 89631,
      first_name: "Jay",
      last_name: "Pawar",
      age: 15,
      phone: "7863214591",
      address: "Surat",
      class: "9th",
      division: "D",
    },

    {
      roll_no: 89632,
      first_name: "Rahul",
      last_name: "Patadiya",
      age: 16,
      phone: "9863245965",
      address: "Surat",
      class: "9th",
      division: "A",
    },

    {
      roll_no: 89633,
      first_name: "Nisha",
      last_name: "Kapoor",
      age: 16,
      phone: "9759448896",
      address: "Bharuch",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89634,
      first_name: "Karan",
      last_name: "Pawar",
      age: 17,
      phone: "9110933585",
      address: "Rajkot",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89635,
      first_name: "Nisha",
      last_name: "Kapoor",
      age: 14,
      phone: "9510443465",
      address: "Ahmedabad",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89636,
      first_name: "Pooja",
      last_name: "Pawar",
      age: 16,
      phone: "9139954204",
      address: "Surat",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89637,
      first_name: "Nisha",
      last_name: "Yadav",
      age: 17,
      phone: "9838594583",
      address: "Ahmedabad",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89638,
      first_name: "Priya",
      last_name: "Joshi",
      age: 13,
      phone: "9708549984",
      address: "Ahmedabad",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89639,
      first_name: "Rahul",
      last_name: "Chopra",
      age: 16,
      phone: "9680897235",
      address: "Vadodara",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89640,
      first_name: "Karan",
      last_name: "Joshi",
      age: 15,
      phone: "9431516191",
      address: "Ahmedabad",
      class: "9th",
      division: "D",
    },
    {
      roll_no: 89641,
      first_name: "Priya",
      last_name: "Joshi",
      age: 14,
      phone: "9156753853",
      address: "Ahmedabad",
      class: "10th",
      division: "A",
    },
    {
      roll_no: 89642,
      first_name: "Rahul",
      last_name: "Kapoor",
      age: 16,
      phone: "9509543588",
      address: "Rajkot",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89643,
      first_name: "Karan",
      last_name: "Chopra",
      age: 17,
      phone: "9312144779",
      address: "Vadodara",
      class: "10th",
      division: "B",
    },
    {
      roll_no: 89644,
      first_name: "Amit",
      last_name: "Joshi",
      age: 14,
      phone: "9806342982",
      address: "Surat",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89645,
      first_name: "Rahul",
      last_name: "Mehta",
      age: 17,
      phone: "9113943184",
      address: "Ahmedabad",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89646,
      first_name: "Rahul",
      last_name: "Mehta",
      age: 17,
      phone: "9423140996",
      address: "Rajkot",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89647,
      first_name: "Priya",
      last_name: "Mehta",
      age: 14,
      phone: "9377322074",
      address: "Ahmedabad",
      class: "9th",
      division: "B",
    },
    {
      roll_no: 89648,
      first_name: "Karan",
      last_name: "Rathod",
      age: 16,
      phone: "9338138034",
      address: "Rajkot",
      class: "8th",
      division: "A",
    },
    {
      roll_no: 89649,
      first_name: "Jay",
      last_name: "Rathod",
      age: 17,
      phone: "9762941810",
      address: "Ahmedabad",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89650,
      first_name: "Jay",
      last_name: "Pawar",
      age: 17,
      phone: "9681076930",
      address: "Vadodara",
      class: "9th",
      division: "A",
    },
    {
      roll_no: 89651,
      first_name: "Priya",
      last_name: "Verma",
      age: 13,
      phone: "9986571649",
      address: "Ahmedabad",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89652,
      first_name: "Ravi",
      last_name: "Shah",
      age: 14,
      phone: "9128963052",
      address: "Rajkot",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89653,
      first_name: "Vikas",
      last_name: "Rathod",
      age: 13,
      phone: "9412530266",
      address: "Ahmedabad",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89654,
      first_name: "Nisha",
      last_name: "Patel",
      age: 15,
      phone: "9400423644",
      address: "Vadodara",
      class: "9th",
      division: "D",
    },
    {
      roll_no: 89655,
      first_name: "Sneha",
      last_name: "Mehta",
      age: 16,
      phone: "9201333873",
      address: "Rajkot",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89656,
      first_name: "Sneha",
      last_name: "Patel",
      age: 16,
      phone: "9849295801",
      address: "Ahmedabad",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89657,
      first_name: "Rahul",
      last_name: "Chopra",
      age: 16,
      phone: "9339028309",
      address: "Vadodara",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89658,
      first_name: "Pooja",
      last_name: "Rathod",
      age: 15,
      phone: "9850436292",
      address: "Ahmedabad",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89659,
      first_name: "Nisha",
      last_name: "Kapoor",
      age: 14,
      phone: "9677670665",
      address: "Bharuch",
      class: "9th",
      division: "A",
    },
    {
      roll_no: 89660,
      first_name: "Ravi",
      last_name: "Mehta",
      age: 16,
      phone: "9253250072",
      address: "Surat",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89661,
      first_name: "Priya",
      last_name: "Mehta",
      age: 13,
      phone: "9972403305",
      address: "Surat",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89662,
      first_name: "Jay",
      last_name: "Joshi",
      age: 17,
      phone: "9521289893",
      address: "Ahmedabad",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89663,
      first_name: "Vikas",
      last_name: "Shah",
      age: 15,
      phone: "9116504732",
      address: "Vadodara",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89664,
      first_name: "Sneha",
      last_name: "Verma",
      age: 13,
      phone: "9189031215",
      address: "Surat",
      class: "8th",
      division: "B",
    },
    {
      roll_no: 89665,
      first_name: "Jay",
      last_name: "Joshi",
      age: 14,
      phone: "9383800489",
      address: "Bharuch",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89666,
      first_name: "Rahul",
      last_name: "Yadav",
      age: 13,
      phone: "9468892099",
      address: "Vadodara",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89667,
      first_name: "Rahul",
      last_name: "Pawar",
      age: 16,
      phone: "9925938970",
      address: "Ahmedabad",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89668,
      first_name: "Jay",
      last_name: "Shah",
      age: 16,
      phone: "9824959885",
      address: "Ahmedabad",
      class: "9th",
      division: "B",
    },
    {
      roll_no: 89669,
      first_name: "Karan",
      last_name: "Pawar",
      age: 16,
      phone: "9406074303",
      address: "Surat",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89670,
      first_name: "Rahul",
      last_name: "Mehta",
      age: 15,
      phone: "9861865933",
      address: "Vadodara",
      class: "9th",
      division: "D",
    },
    {
      roll_no: 89671,
      first_name: "Nisha",
      last_name: "Yadav",
      age: 16,
      phone: "9252669343",
      address: "Rajkot",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89672,
      first_name: "Sneha",
      last_name: "Rathod",
      age: 15,
      phone: "9208797153",
      address: "Ahmedabad",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89673,
      first_name: "Rahul",
      last_name: "Shah",
      age: 14,
      phone: "9715954032",
      address: "Vadodara",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89674,
      first_name: "Sneha",
      last_name: "Yadav",
      age: 14,
      phone: "9398561087",
      address: "Bharuch",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89675,
      first_name: "Sneha",
      last_name: "Shah",
      age: 15,
      phone: "9395906937",
      address: "Surat",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89676,
      first_name: "Sneha",
      last_name: "Verma",
      age: 17,
      phone: "9653830970",
      address: "Surat",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89677,
      first_name: "Vikas",
      last_name: "Shah",
      age: 15,
      phone: "9389095838",
      address: "Bharuch",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89678,
      first_name: "Pooja",
      last_name: "Rathod",
      age: 13,
      phone: "9285124881",
      address: "Rajkot",
      class: "10th",
      division: "D",
    },
    {
      roll_no: 89679,
      first_name: "Amit",
      last_name: "Pawar",
      age: 15,
      phone: "9661775860",
      address: "Bharuch",
      class: "10th",
      division: "D",
    },
    {
      roll_no: 89680,
      first_name: "Karan",
      last_name: "Shah",
      age: 15,
      phone: "9145155054",
      address: "Rajkot",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89681,
      first_name: "Karan",
      last_name: "Joshi",
      age: 14,
      phone: "9100286308",
      address: "Surat",
      class: "10th",
      division: "A",
    },
    {
      roll_no: 89682,
      first_name: "Karan",
      last_name: "Verma",
      age: 14,
      phone: "9252578141",
      address: "Bharuch",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89683,
      first_name: "Nisha",
      last_name: "Yadav",
      age: 15,
      phone: "9808962388",
      address: "Vadodara",
      class: "10th",
      division: "A",
    },
    {
      roll_no: 89684,
      first_name: "Nisha",
      last_name: "Patel",
      age: 14,
      phone: "9130180308",
      address: "Rajkot",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89685,
      first_name: "Priya",
      last_name: "Verma",
      age: 14,
      phone: "9904957198",
      address: "Bharuch",
      class: "9th",
      division: "A",
    },
    {
      roll_no: 89686,
      first_name: "Ravi",
      last_name: "Rathod",
      age: 14,
      phone: "9899511833",
      address: "Ahmedabad",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89687,
      first_name: "Jay",
      last_name: "Kapoor",
      age: 15,
      phone: "9478773909",
      address: "Ahmedabad",
      class: "8th",
      division: "A",
    },
    {
      roll_no: 89688,
      first_name: "Nisha",
      last_name: "Patel",
      age: 15,
      phone: "9652608970",
      address: "Rajkot",
      class: "9th",
      division: "D",
    },
    {
      roll_no: 89689,
      first_name: "Amit",
      last_name: "Patel",
      age: 16,
      phone: "9350213483",
      address: "Vadodara",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89690,
      first_name: "Vikas",
      last_name: "Rathod",
      age: 15,
      phone: "9206344863",
      address: "Rajkot",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89691,
      first_name: "Karan",
      last_name: "Mehta",
      age: 16,
      phone: "9162138081",
      address: "Rajkot",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89692,
      first_name: "Nisha",
      last_name: "Shah",
      age: 13,
      phone: "9282779593",
      address: "Ahmedabad",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89693,
      first_name: "Amit",
      last_name: "Mehta",
      age: 13,
      phone: "9151310693",
      address: "Rajkot",
      class: "10th",
      division: "A",
    },
    {
      roll_no: 89694,
      first_name: "Ravi",
      last_name: "Joshi",
      age: 13,
      phone: "9820699639",
      address: "Bharuch",
      class: "9th",
      division: "B",
    },
    {
      roll_no: 89695,
      first_name: "Vikas",
      last_name: "Shah",
      age: 17,
      phone: "9833718670",
      address: "Vadodara",
      class: "9th",
      division: "D",
    },
    {
      roll_no: 89696,
      first_name: "Priya",
      last_name: "Verma",
      age: 14,
      phone: "9556898729",
      address: "Vadodara",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89697,
      first_name: "Karan",
      last_name: "Rathod",
      age: 16,
      phone: "9410991167",
      address: "Vadodara",
      class: "8th",
      division: "A",
    },
    {
      roll_no: 89698,
      first_name: "Vikas",
      last_name: "Kapoor",
      age: 15,
      phone: "9786754758",
      address: "Vadodara",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89699,
      first_name: "Karan",
      last_name: "Patel",
      age: 17,
      phone: "9127853807",
      address: "Vadodara",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89700,
      first_name: "Rahul",
      last_name: "Verma",
      age: 13,
      phone: "9714737426",
      address: "Bharuch",
      class: "9th",
      division: "D",
    },
    {
      roll_no: 89701,
      first_name: "Priya",
      last_name: "Pawar",
      age: 14,
      phone: "9365132856",
      address: "Bharuch",
      class: "10th",
      division: "B",
    },
    {
      roll_no: 89702,
      first_name: "Vikas",
      last_name: "Joshi",
      age: 17,
      phone: "9133637848",
      address: "Ahmedabad",
      class: "10th",
      division: "A",
    },
    {
      roll_no: 89703,
      first_name: "Vikas",
      last_name: "Pawar",
      age: 15,
      phone: "9155843452",
      address: "Surat",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89704,
      first_name: "Vikas",
      last_name: "Patel",
      age: 13,
      phone: "9678062859",
      address: "Rajkot",
      class: "10th",
      division: "B",
    },
    {
      roll_no: 89705,
      first_name: "Pooja",
      last_name: "Rathod",
      age: 16,
      phone: "9931289155",
      address: "Surat",
      class: "9th",
      division: "C",
    },
    {
      roll_no: 89706,
      first_name: "Priya",
      last_name: "Chopra",
      age: 14,
      phone: "9103126278",
      address: "Rajkot",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89707,
      first_name: "Pooja",
      last_name: "Verma",
      age: 17,
      phone: "9158757783",
      address: "Rajkot",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89708,
      first_name: "Priya",
      last_name: "Kapoor",
      age: 15,
      phone: "9149199948",
      address: "Vadodara",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89709,
      first_name: "Rahul",
      last_name: "Mehta",
      age: 14,
      phone: "9775827600",
      address: "Rajkot",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89710,
      first_name: "Rahul",
      last_name: "Chopra",
      age: 17,
      phone: "9800978695",
      address: "Surat",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89711,
      first_name: "Amit",
      last_name: "Verma",
      age: 17,
      phone: "9774030913",
      address: "Surat",
      class: "10th",
      division: "A",
    },
    {
      roll_no: 89712,
      first_name: "Pooja",
      last_name: "Patel",
      age: 14,
      phone: "9960333116",
      address: "Ahmedabad",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89713,
      first_name: "Nisha",
      last_name: "Pawar",
      age: 14,
      phone: "9677795809",
      address: "Ahmedabad",
      class: "10th",
      division: "B",
    },
    {
      roll_no: 89714,
      first_name: "Jay",
      last_name: "Rathod",
      age: 16,
      phone: "9994849546",
      address: "Bharuch",
      class: "10th",
      division: "E",
    },
    {
      roll_no: 89715,
      first_name: "Amit",
      last_name: "Verma",
      age: 16,
      phone: "9129525413",
      address: "Vadodara",
      class: "8th",
      division: "E",
    },
    {
      roll_no: 89716,
      first_name: "Pooja",
      last_name: "Joshi",
      age: 17,
      phone: "9489980478",
      address: "Bharuch",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89717,
      first_name: "Sneha",
      last_name: "Rathod",
      age: 13,
      phone: "9918912403",
      address: "Surat",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89718,
      first_name: "Sneha",
      last_name: "Pawar",
      age: 15,
      phone: "9999720581",
      address: "Rajkot",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89719,
      first_name: "Karan",
      last_name: "Pawar",
      age: 16,
      phone: "9514057695",
      address: "Bharuch",
      class: "9th",
      division: "D",
    },
    {
      roll_no: 89720,
      first_name: "Pooja",
      last_name: "Mehta",
      age: 16,
      phone: "9325713637",
      address: "Ahmedabad",
      class: "9th",
      division: "B",
    },
    {
      roll_no: 89721,
      first_name: "Nisha",
      last_name: "Shah",
      age: 16,
      phone: "9727849269",
      address: "Surat",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89722,
      first_name: "Vikas",
      last_name: "Chopra",
      age: 17,
      phone: "9234864906",
      address: "Ahmedabad",
      class: "9th",
      division: "A",
    },
    {
      roll_no: 89723,
      first_name: "Karan",
      last_name: "Yadav",
      age: 14,
      phone: "9381501309",
      address: "Ahmedabad",
      class: "10th",
      division: "D",
    },
    {
      roll_no: 89724,
      first_name: "Sneha",
      last_name: "Pawar",
      age: 17,
      phone: "9116417092",
      address: "Surat",
      class: "8th",
      division: "D",
    },
    {
      roll_no: 89725,
      first_name: "Priya",
      last_name: "Mehta",
      age: 15,
      phone: "9337774593",
      address: "Ahmedabad",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89726,
      first_name: "Sneha",
      last_name: "Pawar",
      age: 16,
      phone: "9783886496",
      address: "Bharuch",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89727,
      first_name: "Sneha",
      last_name: "Patel",
      age: 15,
      phone: "9301268892",
      address: "Vadodara",
      class: "10th",
      division: "C",
    },
    {
      roll_no: 89728,
      first_name: "Karan",
      last_name: "Chopra",
      age: 14,
      phone: "9236472136",
      address: "Bharuch",
      class: "8th",
      division: "C",
    },
    {
      roll_no: 89729,
      first_name: "Karan",
      last_name: "Mehta",
      age: 17,
      phone: "9800571730",
      address: "Rajkot",
      class: "9th",
      division: "E",
    },
    {
      roll_no: 89730,
      first_name: "Sneha",
      last_name: "Kapoor",
      age: 15,
      phone: "9976323697",
      address: "Surat",
      class: "8th",
      division: "A",
    },
  ]);
  return (
    <>
      <h1>Students Table</h1>

      <center>
        <table border="1">
          <thead>
            <tr>
              <th>No</th>
              <th>Roll No</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Age</th>
              <th>Phone</th>
              <th>Address</th>
              <th>Class</th>
              <th>Division</th>
              <th>Action</th>
            </tr>
          </thead>

          <tbody>
            {allStudents.map((stud, index) => (
              <tr key={index}>
                <td>{index + 1}</td>
                <td>{stud.roll_no}</td>
                <td>{stud.first_name}</td>
                <td>{stud.last_name}</td>
                <td>{stud.age}</td>
                <td>{stud.phone}</td>
                <td>{stud.address}</td>
                <td>{stud.class}</td>
                <td>{stud.division}</td>
                <td>
                  <button>✏️</button>
                  <button>🗑️</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </center>
    </>
  );
}

export default App;
